class Category < ApplicationRecord

  has_many :project_categories
  has_many :projects, through: :project_categories

  CATEGORIES = [
    'Tecnología General',
    'Inteligencia Artificial',
    'Desarrollo de Software',
    'Desarrollo Web',
    'Aplicaciones Móviles',
    'Ciberseguridad',
    'Big Data y Ciencia de Datos',
    'Blockchain',
    'Internet de las Cosas (IoT)',
    'Cloud Computing y Redes',
    'Blockchain y Criptografía',
    'Automatización y DevOps',
    'Realidad Virtual y Aumentada',
    'IoT Industrial',
    'Ciudades Inteligentes',
    'Drones y Vehículos Autónomos',
    'Diseño Gráfico y Arte Digital',
    'UX/UI y Experiencia de Usuario',
    'Producción Audiovisual',
    'Fotografía',
    'Cine y Televisión',
    'Edición de Video',
    'Música y Sonido',
    'Gaming y Diseño de Juegos',
    'Streaming y Creación de Contenido',
    'Energías Renovables y Eficiencia Energética',
    'Cambio Climático y Sostenibilidad',
    'Reciclaje y Conservación de la Biodiversidad',
    'Gestión de Residuos y Agua',
    'Telemedicina y Salud Pública',
    'Nutrición y Rehabilitación',
    'Deporte y Fitness',
    'Gestión Empresarial y Startups',
    'Innovación Empresarial',
    'Finanzas y Banca',
    'Banca y Seguros',
    'Gestión de Proyectos',
    'Liderazgo y Coaching',
    'Educación General',
    'EdTech y Gamificación',
    'Ciencias Sociales y Humanidades',
    'Educación STEM y Ciencias',
    'Investigación Científica',
    'Divulgación Científica',
    'Astronomía y Física',
    'Química y Matemáticas',
    'Políticas Públicas y Derecho',
    'Seguridad Ciudadana y Defensa',
    'Gobierno Electrónico y Transparencia',
    'Ayuda Humanitaria y Proyectos Comunitarios',
    'Movilidad Urbana y Transporte Público',
    'Transporte y Logística General',
    'Cadena de Suministro',
    'Turismo y Hotelería',
    'Alimentación y Gastronomía',
    'Moda y Textil',
    'Agricultura, Ganadería y Pesca',
    'Arquitectura y Urbanismo',
    'Construcción y Obra Civil'
  ]
end
